x_path: /ix/djishnu/Aaron/3_collabs/1_Torok_Jscl_ER/ER_analysis/6_LAFAYATIS_DATA/cross_pred_use_losai_to_mrss/recluster_all_LS_LoSAI/delta0.1_lambda1/orig_x.csv
y_path: /ix/djishnu/Aaron/3_collabs/1_Torok_Jscl_ER/ER_analysis/6_LAFAYATIS_DATA/cross_pred_use_losai_to_mrss/recluster_all_LS_LoSAI/delta0.1_lambda1/orig_y.csv
out_path: /ix/djishnu/Aaron/3_collabs/1_Torok_Jscl_ER/ER_analysis/2_FINAL_RESULTS/LS_LoSAI_for_MRSS_SLIDECV/spec01/
k: 5.0
y_factor: no
y_levels: NULL
eval_type: corr
rep_cv: 25
nreps: 25.0
alpha_level: 0.05
thresh_fdr: 0.2
permute: yes
std_cv: no
std_y: no
benchmark: no
delta: 0.01
lambda: 0.1
lasso: no
plsr: yes
pcr: yes
spec: 0.1
z_path: /ix/djishnu/Aaron/3_collabs/1_Torok_Jscl_ER/ER_analysis/2_FINAL_RESULTS/LS_LoSAI_for_MRSS_SLIDECV/z_mat.csv
niter: 50.0
parallel: yes
method: 4.0
ncore: 16.0
fdr: 0.2
f_size: 81
